function lmin = lmin(in1)
%LMIN
%    LMIN = LMIN(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    28-Nov-2021 12:58:56

x1 = in1(1,:);
x2 = in1(2,:);
x3 = in1(3,:);
x4 = in1(4,:);
x5 = in1(5,:);
x6 = in1(6,:);
lmin = x1.^2.*1.0e+1+x2.^2.*1.0e+1+x3.^2.*1.0e+1+x4.^2./1.0e+1+x5.^2./1.0e+1+x6.^2./1.0e+1;
