function G_xi = G_xi(in1)
%G_xi
%    G_xi = G_xi(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    03-Dec-2021 09:12:06

xi1 = in1(1,:);
xi2 = in1(2,:);
xi3 = in1(3,:);
xi4 = in1(4,:);
xi5 = in1(5,:);
xi6 = in1(6,:);
xi7 = in1(7,:);
xi8 = in1(8,:);
xi9 = in1(9,:);
xi10 = in1(10,:);
t2 = cos(xi1);
t3 = sin(xi1);
t4 = xi1+xi4+xi5;
t5 = cos(t4);
t6 = sin(t4);
t7 = t4+xi8+xi9;
t8 = sin(t7);
t9 = t6.*xi6.*1.96133;
t10 = t6.*xi7.*9.806649999999999e-1;
t11 = t8.*xi10.*9.806649999999999e-1;
t12 = t9+t10+t11;
mt1 = [t12+t3.*xi2.*2.941995+t3.*xi3.*1.96133,t2.*(-2.941995),t2.*(-1.96133),t12,t12,t5.*(-1.96133)];
mt2 = [t5.*(-9.806649999999999e-1),t11,t11,cos(t7).*(-9.806649999999999e-1),0.0,0.0];
G_xi = reshape([mt1,mt2],12,1);
