function J_xi = J_xi(in1)
%J_xi
%    J_xi = J_xi(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    03-Dec-2021 09:12:03

xi1 = in1(1,:);
xi2 = in1(2,:);
xi3 = in1(3,:);
xi4 = in1(4,:);
xi5 = in1(5,:);
xi6 = in1(6,:);
xi7 = in1(7,:);
xi8 = in1(8,:);
xi9 = in1(9,:);
xi10 = in1(10,:);
xi11 = in1(11,:);
t2 = cos(xi1);
t3 = sin(xi1);
t4 = xi10+xi11;
t5 = xi1+xi4+xi5;
t6 = cos(t5);
t7 = -t2;
t8 = sin(t5);
t9 = t5+xi8+xi9;
t10 = t6.*xi6;
t11 = t6.*xi7;
t12 = t8.*xi6;
t13 = t8.*xi7;
t14 = cos(t9);
t15 = sin(t9);
t16 = -t6;
t17 = t15.*xi10;
t18 = t15.*xi11;
t19 = t14.*xi10;
t20 = t14.*xi11;
t21 = -t14;
t22 = t4.*t14;
t23 = t4.*t15;
t24 = t10+t11+t19+t20;
t25 = t12+t13+t17+t18;
J_xi = reshape([t24+t2.*xi2+t2.*xi3,t25+t3.*xi2+t3.*xi3,t3,t7,t3,t7,t24,t25,t24,t25,t8,t16,t8,t16,t22,t23,t22,t23,t15,t21,t15,t21,0.0,0.0],[2,12]);
