function Jm_dot_limit = Jm_dot_limit(in1)
%Jm_dot_limit
%    Jm_dot_limit = Jm_dot_limit(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    03-Dec-2021 09:12:08

q_dot1 = in1(1,:);
q_dot2 = in1(2,:);
q_dot3 = in1(3,:);
t2 = q_dot1./8.0e+1;
t3 = q_dot2./8.0e+1;
t4 = q_dot3./8.0e+1;
t5 = -t2;
t6 = -t3;
t7 = -t4;
Jm_dot_limit = reshape([0.0,t5,t5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t6,t6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t7,t7,0.0],[12,3]);
