function Jm_limit = Jm_limit
%Jm_limit
%    Jm_limit = Jm_limit

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    03-Dec-2021 09:12:08

Jm_limit = reshape([1.0./2.0,0.0,0.0,1.0./2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0./2.0,0.0,0.0,1.0./2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0./2.0,0.0,0.0,1.0./2.0],[12,3]);
