function map_limit = map_limit
%MAP_LIMIT
%    MAP_LIMIT = MAP_LIMIT

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    03-Dec-2021 09:12:08

map_limit = [0.0;3.0./2.0e+1;3.0./2.0e+1;0.0;0.0;3.0./2.0e+1;3.0./2.0e+1;0.0;0.0;3.0./2.0e+1;3.0./2.0e+1;0.0];
