function map = map_singular(in1)
%MAP_SINGULAR
%    MAP = MAP_SINGULAR(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    03-Dec-2021 09:12:06

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
t2 = 1.0./q1;
t3 = 1.0./q2;
t4 = 1.0./q3;
t5 = q1./2.0;
t6 = q2./2.0;
t7 = q3./2.0;
t8 = sin(t5);
t9 = sin(t6);
t10 = sin(t7);
t11 = t2.*t8.*(3.0./1.0e+1);
t12 = t3.*t9.*(3.0./1.0e+1);
t13 = t4.*t10.*(3.0./1.0e+1);
map = [t5;t11;t11;t5;t6;t12;t12;t6;t7;t13;t13;t7];
